GET  http://localhost:3000/students.json
###
### CREATE STUDENT
POST http://localhost:3000/students
Content-Type: application/json

{
  "name": ""
  "name":
  "name":
  "name":
  "name":
  "name":
  "name":
  "name":
  "name":
}