@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50X2lkIjoyLCJleHAiOjE2NzI1MTIxMjl9.H8RSc4ZzrJtrHD1UqK5ix438lX1c3twQAqqJPmsPmQg

### Index
GET http://localhost:3000/skills
### Show
GET http://localhost:3000/skills/1
### Create
POST http://localhost:3000/skills 
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "python": false, 
  "javascript": false,
  "java": true,
  "csharp": false,
  "c": true,
  "Cplus": true,
  "go": false,
  "r": false,
  "swift": true,
  "php": false,
  "other": "Ruby"
}

### UPDATE
PATCH http://localhost:3000/skills/1 
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "python": false,
  "javascript": true,
  "java": false,
  "csharp": false,
  "c": false,
  "cplus": true,
  "go": false,
  "r": false,
  "swift": false,
  "php": true,
  "other": "Ruby, Ruby on Rails"
}
### DELETE
DELETE http://localhost:3000/skills/7
Authorization: Bearer {{jwt}}