# @jwt = 

### STUDENTS INDEX
GET  http://localhost:3000/students.json
###
GET http://localhost:3000/students/6.json
### CREATE STUDENT
POST http://localhost:3000/students.json
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "first_name": "Johnny",
  "last_name":  "Test",
  "email":  "test60@example.com",
  "phone_number": "123-456-4789",
  "short_bio":  "I do the test ",
  "linkedin_url": "linkedin.com",
  "twitter_handle":"twitter.com/test",
  "online_resume_url": "resume.com/test",
  "github_url": "github.com/test",
  "photo_url": "https://static.wikia.nocookie.net/lotr/images/2/20/Sam.jpg/revision/latest?cb=20070623123241",
  "personal_website_url": "example.com",
  "password": "password",
  "password_confirmation": "password"

}

###
DELETE http://localhost:3000/students/6.json

### Edit one student
PATCH  http://localhost:3000/students/7
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "first_name": "Sam",
  "last_name":  "Wise",
  "email":  "sam@example.com",
  "phone_number": "123-456-4789",
  "short_bio":  "I am the best Hobbit",
  "linkedin_url": "linkedin.com/in/samwise",
  "twitter_handle":"twitter.com/Samwise",
  "online_resume_url": "Samwise.com/resume",
 "github_url": "github.com/Samwise",
 "photo_url": "https://static.wikia.nocookie.net/lotr/images/2/20/Sam.jpg/revision/latest?cb=20070623123241",
 "personal_website_url": "samwise.com/aboutme"
}